### ISSUE TITLE
Create RESTful API and call model prediction from another VM

### ISSUE THREAD

**Issue by levithatcher** [HealthCatalystSLC/healthcareai-py#22]
So basically, we'll host the model and RESTful API on a workstation and make calls to the API from the ETL machine (which will tie in to the platform extensibility point).

In this task, I will use two Azure VMs within a VNet to test this functionality.

Note that the API call (from the SQL Server VM) will not pass values, but will instead make the call to the workstation VM to run the entire script (including pulling data in from the SQL Server VM).

**Comment by Aylr** [comment]
I wonder if wrapping a trained model in flask would be a fast way to accomplish this.
